### ISSUE TITLE
No longer marks a whole line

### ISSUE THREAD

**Issue by robcrocombe** [dusk125/sublime-betterbookmarks#11]
Hey, since v1.1.0 (I assume) the behaviour now works like the built-in Sublime bookmarks, and not how it used to where it marks the whole line. This is still how the readme describes it, and I much prefer the old behaviour. Is this a bug or a planned change? Thanks

**Comment by dusk125** [comment]
Adding a setting flag that will allow you to switch between marking the whole line by default or marking like sublime text marks (selection based).

**Comment by dusk125** [comment]
This issue has been addressed since v1.1.3. Thanks for bringing this up!
