### ISSUE TITLE
All Bookmarks deleted after close / re-open and adding a new one or layer switch

### ISSUE THREAD

**Issue by wowcut** [dusk125/sublime-betterbookmarks#15]
### 1. Summary
After closing and then re-opening Sublime Text all bookmarks disappear when adding a new bookmark (with F11). Also swapping the layers destroys all current bookmarks. This pnly seems to happen after a close/open cycle.

### 2. Expected behavior

Not deleting all existing bookmarks when adding a new one.

### 3. Actual behavior

I can not see bookmarks after file re-opening and adding a new bookmark.

### 4. Settings

My `User\BetterBookmarks.sublime-settings` file

```json
{
	"layer_icons": {
		// This one is the default Sublime bookmark
		"bookmarks": {"icon": "bookmark", "scope": "string"},
		"functions": {"icon": "Packages/Better Bookmarks/icons/function.png", "scope": "comment"},
		"todos": {"icon": "Packages/Better Bookmarks/icons/todo.png", "scope": "comment"},
	}
}
```

### 4. Steps to reproduce

I install BetterBookmarks → I run command `better_bookmarks_mark_line` multiple times → I close file → I re-open file → I can see my bookmarks → I press F11 → all old bookmarks are gone.

### 5. Environment

**Operating system and version:**
Ubuntu 16.04
**Sublime Text:**
Build 3176

Thanks.

_Originally posted by @Kristinita in https://github.com/dusk125/sublime-betterbookmarks/issues/3#issuecomment-263551946_

**Comment by dusk125** [comment]
Thank you for the bug report, your issue is explained by [this](https://github.com/dusk125/sublime-betterbookmarks/issues/12#issuecomment-414804836) and should be fixed in the next version (v1.2.0).

**Comment by wowcut** [comment]
Than you very much for your efforts! I am happy to finally have persistent bookmarks with sublime! The other features I like, too! Nice holidays!

**Comment by dusk125** [comment]
v1.2.0 has been released and your problem should resolve once Package Control sees the new release. Happy Holidays!
