### ISSUE TITLE
Toggle bookmark command

### ISSUE THREAD

**Issue by jamescasin** [dusk125/sublime-betterbookmarks#17]
Is there a way to remove a single bookmark instead of removing all?

**Comment by dusk125** [comment]
Running the same command that was used to mark the line originally should remove that single bookmark:
`{"command": "better_bookmarks", "args": {"subcommand": "mark_line"}}`

Depending on your settings (if you have "marking_mode" set to "selection"), you'll need to run that command with the same selection that was used to originally mark it.
