### ISSUE TITLE
Betterbookmarks icons display problem

### ISSUE THREAD

**Issue by onirix** [dusk125/sublime-betterbookmarks#4]
Icons seems not loaded.

It look like like this :
[https://i.imgur.com/d7jil7A.png](https://i.imgur.com/d7jil7A.png)

**Comment by onirix** [comment]
It’s all right !

After extract plugin with PackageResourceViewer, I change paths in the Settings - User of the package.

From :
"functions": {"icon": "Packages/BetterBookmarks/icons/function.png", "scope": "comment"},
"todos": {"icon": "Packages/BetterBookmarks/icons/todo.png", "scope": "comment"},

To :
"functions": {"icon": "Packages/Better Bookmarks/icons/function.png", "scope": "comment"},
"todos":     {"icon": "Packages/Better Bookmarks/icons/todo.png", "scope": "comment"},

**Comment by dusk125** [comment]
Hmm interesting I'll try to figure out why this happened

**Comment by dusk125** [comment]
Thank you Kristinita for the PR, but this problem is now fixed in version 1.1
